name: markdownlint

on: [pull_request]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run mdl
        uses: actionshub/markdownlint@master
